server:
  port: 8080

spring:
  application:
    name: gateway
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

campus:
  auth:
    token-prefix: ctk_
    expire-seconds: 86400
    remember-expire-seconds: 604800
  remote:
    mode: ${CAMPUS_REMOTE_MODE:http}
    registry:
      enabled: ${CAMPUS_REGISTRY_ENABLED:true}
      host: ${CAMPUS_REGISTRY_HOST:127.0.0.1}
      rpc-port: ${CAMPUS_REGISTRY_RPC_PORT:9090}
      timeout-ms: ${CAMPUS_REGISTRY_TIMEOUT_MS:3000}
      rpc-version: 1
      rpc-serializer: java
    user-service:
      host: 127.0.0.1
      rpc-port: 9091
      timeout-ms: 5000
      rpc-version: 1
      rpc-serializer: java
      base-url: http://127.0.0.1:8081
    product-service:
      host: 127.0.0.1
      rpc-port: 9092
      timeout-ms: 5000
      rpc-version: 1
      rpc-serializer: java
      base-url: http://127.0.0.1:8082
    favorite-service:
      host: 127.0.0.1
      rpc-port: 9093
      timeout-ms: 5000
      rpc-version: 1
      rpc-serializer: java
      base-url: http://127.0.0.1:8083
    message-service:
      host: 127.0.0.1
      rpc-port: 9094
      timeout-ms: 5000
      rpc-version: 1
      rpc-serializer: java
      base-url: http://127.0.0.1:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
