server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${CAMPUS_MYSQL_HOST:127.0.0.1}:${CAMPUS_MYSQL_PORT:3306}/campustrade_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${CAMPUS_MYSQL_USERNAME:root}
    password: ${CAMPUS_MYSQL_PASSWORD:200662.Gd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

campus:
  rpc:
    port: ${CAMPUS_RPC_PORT:9092}
    protocol-version: 1
    serializer: java
    advertise-host: ${CAMPUS_RPC_ADVERTISE_HOST:127.0.0.1}
    registry:
      enabled: ${CAMPUS_REGISTRY_ENABLED:false}
      host: ${CAMPUS_REGISTRY_HOST:127.0.0.1}
      port: ${CAMPUS_REGISTRY_RPC_PORT:9090}
      timeout-ms: ${CAMPUS_REGISTRY_TIMEOUT_MS:3000}
      heartbeat-interval-ms: ${CAMPUS_REGISTRY_HEARTBEAT_INTERVAL_MS:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
