INSERT INTO ct_product (
    product_id,
    seller_id,
    title,
    summary,
    description,
    price,
    original_price,
    category,
    location,
    cover_image_url,
    view_count,
    favorite_count,
    negotiable,
    stock,
    image_urls,
    tags,
    status,
    created_at,
    updated_at
) VALUES
    (
        20001,
        10001,
        'iPad 9 64G',
        'Tablet for class notes',
        'Good condition iPad with charger.',
        1650.00,
        2499.00,
        'Digital',
        'Main Campus',
        'https://example.com/product/ipad-9.jpg',
        120,
        20,
        1,
        1,
        '["https://example.com/product/ipad-9-1.jpg","https://example.com/product/ipad-9-2.jpg"]',
        '["ipad","tablet","study"]',
        'ON_SALE',
        '2026-04-21 10:00:00',
        '2026-04-22 09:30:00'
    ),
    (
        20002,
        10002,
        'Road Bike',
        'City and campus riding',
        '27 speed road bike, lightly used.',
        780.00,
        1399.00,
        'Sports',
        'North Campus',
        'https://example.com/product/road-bike.jpg',
        86,
        12,
        1,
        1,
        '["https://example.com/product/road-bike-1.jpg","https://example.com/product/road-bike-2.jpg"]',
        '["bike","sports"]',
        'ON_SALE',
        '2026-04-20 12:00:00',
        '2026-04-22 09:00:00'
    ),
    (
        20003,
        10003,
        'Java Book Set',
        'Three java books',
        'Includes Effective Java and Spring books.',
        120.00,
        360.00,
        'Books',
        'Main Campus',
        'https://example.com/product/java-books.jpg',
        34,
        5,
        0,
        1,
        '["https://example.com/product/java-books-1.jpg","https://example.com/product/java-books-2.jpg"]',
        '["java","book"]',
        'OFF_SHELF',
        '2026-04-18 15:10:00',
        '2026-04-21 13:20:00'
    ),
    (
        20004,
        10001,
        'Desk Lamp',
        'Eye-care lamp',
        'Perfect for dormitory desk study.',
        55.00,
        139.00,
        'Home',
        'South Campus',
        'https://example.com/product/desk-lamp.jpg',
        43,
        8,
        1,
        2,
        '["https://example.com/product/desk-lamp-1.jpg","https://example.com/product/desk-lamp-2.jpg"]',
        '["lamp","dorm"]',
        'ON_SALE',
        '2026-04-19 19:00:00',
        '2026-04-22 11:40:00'
    )
ON DUPLICATE KEY UPDATE
    seller_id = VALUES(seller_id),
    title = VALUES(title),
    summary = VALUES(summary),
    description = VALUES(description),
    price = VALUES(price),
    original_price = VALUES(original_price),
    category = VALUES(category),
    location = VALUES(location),
    cover_image_url = VALUES(cover_image_url),
    view_count = VALUES(view_count),
    favorite_count = VALUES(favorite_count),
    negotiable = VALUES(negotiable),
    stock = VALUES(stock),
    image_urls = VALUES(image_urls),
    tags = VALUES(tags),
    status = VALUES(status),
    updated_at = VALUES(updated_at);
